server:
  port: 8080

spring:
  application:
    name: APP_NAME

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: DB_SCHEMA
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration/base
    schemas: DB_SCHEMA
    baseline-on-migrate: true

  sql:
    init:
      mode: never